config/routes.rb
FolioManage::Application.routes.draw do
  get "admin/index"
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  resources :users

  get "stocks/index"

  match "/stocks/add_new_stock" => "stocks#add_new_stock"
  resources :stocks

  root :to => 'stocks#index', :as => 'stocks'

  

end

app/models/stock.rb
class Stock < ActiveRecord::Base

  validates :symbol, :holding, :price, :presence=>true
  validates :holding, :numericality => {:greater_than_or_equal_to => 0}
  validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
  validates :symbol, :uniqueness => true
  
end

app/models/user.rb
require 'digest/sha2'
class User < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true
  validates :password, :confirmation => true
  attr_accessor :password_confirmation
  attr_reader :password
  validate :password_must_be_present
  def User.authenticate(name, password)
    if user = find_by_name(name)
      if user.hashed_password == encrypt_password(password, user.salt)
        user
      end
    end
  end
  def User.encrypt_password(password, salt)
    Digest::SHA2.hexdigest(password + "wibble" + salt)
  end
  # 'password' is a virtual attribute
  def password=(password)
    @password = password
    if password.present?
      generate_salt
      self.hashed_password = self.class.encrypt_password(password, salt)
    end
  end
  private
  def password_must_be_present
    errors.add(:password, "Missing password" ) unless hashed_password.present?
  end
  def generate_salt
    self.salt = self.object_id.to_s + rand.to_s
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @time=Time.now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authorize
  protect_from_forgery

protected
def authorize
  unless User.find_by_id(session[:user_id])
    redirect_to login_url, :notice => "Please log in"
  end
end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize
  def new
  end

  def create
    if user = User.authenticate(params[:name], params[:password])
      session[:user_id] = user.id
      redirect_to stocks_url
    else
      redirect_to login_url, :alert => "Invalid user/password combination"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to stocks_url, :notice => "Logged out"
  end
end

app/controllers/stocks_controller.rb
require 'open-uri'
require 'csv'


class StocksController < ApplicationController

  
  #skip_before_filter :authorize, :only => [:new, :create]
  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all
    query_string = ""
    @stocks.each do |stock|
      query_string = query_string + "+" + stock.symbol
    end
    url = "http://finance.yahoo.com/d/quotes.csv?s=#{query_string}&f=nl1c1"
    csv = CSV.parse(open(url).read)
    @result = Array.new
    #parse csv data
    csv.each do |row|
      puts row
      @result += row
    end
    @counter=0
    count=0
    @hash = Hash.new
    @stocks_array=Array.new

    @stocks.each do |stock|
      @hash["symbol"] = stock.symbol
      @hash["name"]= stock.name
      count=count+1
      @hash["holding"]= stock.holding
      @hash["price"]= stock.price
      @hash["current_price"]= @result[count]
      count=count+1
      @hash["daily_gain"]=stock.holding.to_f * @result[count].to_f
      count=count+1
      @hash["overall_gain"]=(stock.price.to_f-stock.price.to_f) * stock.holding.to_f
      @hash["current_value"]=@hash["current_price"].to_f * stock.holding.to_f
      @total_value = @total_value.to_f + @hash["current_value"].to_f
      @total_investment = @total_investment.to_f + (stock.price.to_f * stock.holding.to_f)
      @stocks_array.push(@hash)
    end
    @total_gain=@total_value.to_f-@total_investment.to_f


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stocks }
    end
  end

  def add_new_stock
    @stock=Stock.new
    @stock.symbol = params[:symbol]
    @stock.name = params[:sname]
    @stock.holding = params[:hold]
    @stock.price = params[:price]
    @stock.save

  end
  # GET /stocks/1
  # GET /stocks/1.json
  def show
    @stock = Stock.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stock }
    end
  end

  # GET /stocks/new
  # GET /stocks/new.json
  def new
    @stock = Stock.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stock }
    end
  end

  # GET /stocks/1/edit
  def edit
    @stock = Stock.find(params[:id])
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(params[:stock])

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render json: @stock, status: :created, location: @stock }
      else
        format.html { render action: "new" }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stocks/1
  # PUT /stocks/1.json
  def update
    @stock = Stock.find(params[:id])

    respond_to do |format|
      if @stock.update_attributes(params[:stock])
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock = Stock.find(params[:id])
    @stock.destroy

    respond_to do |format|
      format.html { redirect_to stocks_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: "User #{@user.name} was successfully created." }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to users_url, notice: "User #{@user.name} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Welcome</h1>
It's <%= @time %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FolioManage</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if session[:user_id] %>
<%= button_to 'Logout' , logout_path, :method => :delete %>
<% end %>
<%= yield %>

</body>
</html>

app/views/stocks/_form.html.erb
<%= form_for(@stock) do |f| %>
  <% if @stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% @stock.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :symbol %><br />
    <%= f.text_field :symbol %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :holding %><br />
    <%= f.number_field :holding %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stocks/add_new_stock.erb
Stock successfully created!!!
<%= link_to 'Back', stocks_path %>

app/views/stocks/edit.html.erb
<h1>Editing stock</h1>

<%= render 'form' %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>

    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js"></script>
    <!--[if lt IE 9]>
    <script type="text/javascript" src="/javascripts/excanvas/excanvas.js"></script>
    <![endif]-->
    <script type="text/javascript" src="/javascripts/spinners/spinners.min.js"></script>
    <script type="text/javascript" src="/javascripts/lightview/lightview.js"></script>

    <link rel="stylesheet" type="text/css" href="/stylesheets/lightview/lightview.css"/>

    <meta charset="utf-8">
    <title>Portfolio Management</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>
    <link href="/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="../assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Stock Control</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="mailto:rohanmoitra@gmail.com?Subject=Feedback & Suggestions">Contact</a></li>
            </ul>

          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
        <h2>My Portfolio</h2>

          <table border="1">
              <col width="50">
              <col width="100">
              <col width="50">
              <col width="100">
              <col width="100">
              <col width="100"> 
            <tr>
              <th>Symbol</th>
              <th>Name</th>
              <th>Holding</th>
              <th>Inv Price</th>
              <th>Current Price</th>
              <th>Day's Gain</th>
              <th>Overall Gain</th>
              <th>Current Value</th>
              <th></th>
              <th></th>
              <th></th>
            </tr>

<% @stocks.each do |stock| %>
            <tr>
              <td align="center"><a href="http://finance.yahoo.com/q?s=<%= stock.symbol %> " class="lightview" data-lightview-type="iframe"
                 data-lightview-options="width: 1000, height: '100%'"><%= stock.symbol %></a></td>
              <td align="center"><%= stock.name %></td>
              <%@counter=@counter+1%>
              <td align="center"><%= stock.holding %></td>
              <td align="center"><%= stock.price %></td>
              <% @current_price = @result[@counter] %>
              <td align="center"><%= @current_price %></td>
              <% @counter=@counter+1 %>
              <% @daily_gain = stock.holding.to_f * @result[@counter].to_f %>
              <td align="center"><%= @daily_gain.round(2) %>
                <% if @daily_gain > 0 %>
                  <img src="/img/upArrow.png"> </img>
                <%else%>
                  <img src="/img/down_arrow.png"> </img>
                <%end%>
              </td>
                <%  @counter=@counter+1 %>
                <% @overall_gain = (@current_price.to_f-stock.price.to_f) * stock.holding.to_f %>
                <td align="center"><%=@overall_gain.round=%>
                <% if @overall_gain > 0 %>
                  <img src="/img/upArrow.png"> </img>
                <%else%>
                  <img src="/img/down_arrow.png"> </img>
                <%end%>
              </td>
              <% @current_value = @current_price.to_f * stock.holding.to_f %>
                      <td align="center"><%=@current_value.round(2)%></td>
             
      
              <td><%= link_to 'Show', stock %></td>
              <td><%= link_to 'Edit', edit_stock_path(stock)%></td>
              <td><%= link_to 'Destroy', stock, confirm: 'Are you sure?', method: :delete %></td>
            </tr>
          <% end %>
          </table>
        <br />

        <%= link_to 'New Stock', new_stock_path %>
      </div>

      <!-- Example row of columns -->
      <div class="row">
        <div class="span4">
          <h2>My Networth </h2> 
          <p> Networth: <%= @total_value.round(2) %>
          <% if @total_value.round(2) > @total_investment.round(2) %>
            <img src="/img/upArrow.png"> </img></p> 
          <%else%>
            <img src="/img/down_arrow.png"> </img>
          <%end%>
            <p> Total Investment: <%= @total_investment.round(2) %></p>
          
          <p> Total Portfolio Gain: <%= @total_gain.round(2) %>
          <% if @total_gain > 0 %>
            <img src="/img/upArrow.png"> </img> </p> 
          <%else%>
            <img src="/img/down_arrow.png"> </img>
          <%end%>
          
        </div>
       
          
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; Rohan Moitra 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/js/jquery.js"></script>
    <script src="/js/bootstrap-transition.js"></script>
    <script src="/js/bootstrap-alert.js"></script>
    <script src="/js/bootstrap-modal.js"></script>
    <script src="/js/bootstrap-dropdown.js"></script>
    <script src="/js/bootstrap-scrollspy.js"></script>
    <script src="/js/bootstrap-tab.js"></script>
    <script src="/js/bootstrap-tooltip.js"></script>
    <script src="/js/bootstrap-popover.js"></script>
    <script src="/js/bootstrap-button.js"></script>
    <script src="/js/bootstrap-collapse.js"></script>
    <script src="/js/bootstrap-carousel.js"></script>
    <script src="/js/bootstrap-typeahead.js"></script>

  </body>
</html>

app/views/stocks/new.html.erb
<h1>New stock</h1>

<script type="text/javascript">
function createNewMember() {
var link = '/stocks/add_new_stock?symbol=';
link = link + document.getElementById('stock_symbol').value + '&sname=' ;
link = link + document.getElementById('stock_name').value+ '&hold=';
link = link + document.getElementById('stock_holding').value+'&price=';
link = link + document.getElementById('stock_price').value;
document.location.href = link;
}
</script>
<div class="field">
<label for="stock_symbol">Symbol</label><br />
<input id="stock_symbol" name="stock[symbol]" size="30" type="text" />
</div>
<div class="field">
<label for="stock_name">Name</label><br />
<input id="stock_name" name="stock[name]" size="30" type="text" />
</div>
<div class="field">
<label for="stock_holding">Holding</label><br />
<input id="stock_holding" name="stock[holding]" type="number" />
</div>
<div class="field">
<label for="stock_price">Price</label><br />
<input id="stock_price" name="stock[price]" size="30" type="text" />
</div>

<input type="button" onClick="createNewMember()" value="Create New Member" />


<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Symbol:</b>
  <%= @stock.symbol %>
</p>

<p>
  <b>Name:</b>
  <%= @stock.name %>
</p>

<p>
  <b>Holding:</b>
  <%= @stock.holding %>
</p>

<p>
  <b>Price:</b>
  <%= @stock.price %>
</p>


<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Username' %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password, 'Password' %><br />
    <%= f.password_field :password, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :password_confirmtion, 'Confirm' %><br />
    <%= f.password_field :password_confirmation, :size=>30 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Hashed password:</b>
  <%= @user.hashed_password %>
</p>

<p>
  <b>Salt:</b>
  <%= @user.salt %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>